--- 
- 
  hosts: localhost
  name: "Creating Sand Box"
  tasks: 
    - 
      ec2: 
        aws_access_key: AKIAJURUPGCARJB2XE4Q
        aws_secret_key: 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
        group: default
        image: "{{ image }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ keypair }}"
        region: "{{ region }}"
      name: "creating EC2"
  vars: 
    image: ami-e13739f6
    instance_type: t2.micro
    keypair: aws1key
    region: us-east-1
